// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC258TtC9BjpfXGK2JAwS2cjfJEe2n6ig0',
    appId: '1:943897185361:web:22d46e2994b41f75017c70',
    messagingSenderId: '943897185361',
    projectId: 'tiendaonline-edc84',
    authDomain: 'tiendaonline-edc84.firebaseapp.com',
    storageBucket: 'tiendaonline-edc84.firebasestorage.app',
    measurementId: 'G-YPW2EN5HNF',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBsEuV-VWRdagxRTxVKK0IY7RAuXGsTSu8',
    appId: '1:943897185361:android:09aa41aa148f401b017c70',
    messagingSenderId: '943897185361',
    projectId: 'tiendaonline-edc84',
    storageBucket: 'tiendaonline-edc84.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAKk3QaTFkR77FftZGm30xTji0rMVkQFkE',
    appId: '1:943897185361:ios:077f04371eccdd9c017c70',
    messagingSenderId: '943897185361',
    projectId: 'tiendaonline-edc84',
    storageBucket: 'tiendaonline-edc84.firebasestorage.app',
    iosBundleId: 'com.example.appNavegacionEstado',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC258TtC9BjpfXGK2JAwS2cjfJEe2n6ig0',
    appId: '1:943897185361:web:83a73179f20ff722017c70',
    messagingSenderId: '943897185361',
    projectId: 'tiendaonline-edc84',
    authDomain: 'tiendaonline-edc84.firebaseapp.com',
    storageBucket: 'tiendaonline-edc84.firebasestorage.app',
    measurementId: 'G-KKRC432DLJ',
  );
}
